-- This migration was generated by `prisma migrate dev --create-only`
-- diffing the current schema against migration history, which also
-- proposed `ALTER TABLE "User" DROP COLUMN "passwordHash"` — deliberately
-- removed from this file. See commit 609b8bb ("Restore the passwordHash
-- migration file the revert deleted"): schema.prisma has no `passwordHash`
-- field on purpose, but the column itself must stay in the database as a
-- permanently-unused nullable column, not get dropped — some deployments
-- may already have `20260913030000_add_password_hash` applied, and nothing
-- anywhere reads or writes this column either way, so there is no reason
-- to touch it here. This migration only adds the Phase 4 "My Layout" /
-- staples / history tables and columns below.
-- AlterTable
ALTER TABLE "GroupGroceryItem" ADD COLUMN     "aisleId" TEXT,
ADD COLUMN     "aisleManuallySet" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "GroupStoreAisle" (
    "id" TEXT NOT NULL,
    "groupId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sortIndex" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "linkedCategory" "GroceryCategory",
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GroupStoreAisle_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GroupStapleItem" (
    "id" TEXT NOT NULL,
    "groupId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" "GroceryCategory" NOT NULL,
    "defaultQuantityText" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "addedByUserId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GroupStapleItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GroupGroceryHistoryEntry" (
    "id" TEXT NOT NULL,
    "groupId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "normalizedName" TEXT NOT NULL,
    "category" "GroceryCategory" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GroupGroceryHistoryEntry_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "GroupStoreAisle_groupId_idx" ON "GroupStoreAisle"("groupId");

-- CreateIndex
CREATE INDEX "GroupStoreAisle_groupId_sortIndex_idx" ON "GroupStoreAisle"("groupId", "sortIndex");

-- CreateIndex
CREATE INDEX "GroupStapleItem_groupId_idx" ON "GroupStapleItem"("groupId");

-- CreateIndex
CREATE INDEX "GroupGroceryHistoryEntry_groupId_idx" ON "GroupGroceryHistoryEntry"("groupId");

-- CreateIndex
CREATE UNIQUE INDEX "GroupGroceryHistoryEntry_groupId_normalizedName_key" ON "GroupGroceryHistoryEntry"("groupId", "normalizedName");

-- CreateIndex
CREATE INDEX "GroupGroceryItem_groupId_aisleId_idx" ON "GroupGroceryItem"("groupId", "aisleId");

-- AddForeignKey
ALTER TABLE "GroupGroceryItem" ADD CONSTRAINT "GroupGroceryItem_aisleId_fkey" FOREIGN KEY ("aisleId") REFERENCES "GroupStoreAisle"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GroupStoreAisle" ADD CONSTRAINT "GroupStoreAisle_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GroupStapleItem" ADD CONSTRAINT "GroupStapleItem_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GroupStapleItem" ADD CONSTRAINT "GroupStapleItem_addedByUserId_fkey" FOREIGN KEY ("addedByUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GroupGroceryHistoryEntry" ADD CONSTRAINT "GroupGroceryHistoryEntry_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE;
